[package]
name = "day19"
version = "0.1.0"
authors = ["Wilk Maia <wilkmaia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../utils" }
regex = "1.4.2"
